services:
  tsb_app:
    container_name: tsb_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - tsb_postgres
    environment:
      TELEGRAM_BOT_TOKEN: "$TELEGRAM_BOT_TOKEN"
      DEBUG_CHAT_ID: "$DEBUG_CHAT_ID"
      DATABASE_URL: "postgres://tagstickerbot:p4ssw0rd@tsb_postgres:5432/tagstickerbot"
      LOG_LEVEL: "info"
    networks:
      - "global_network"

  tsb_postgres:
    container_name: tsb_postgres
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "tagstickerbot"
      POSTGRES_USER: "tagstickerbot"
      POSTGRES_PASSWORD: "p4ssw0rd"
    volumes:
      - "./local/postgres-data:/var/lib/postgresql/data"
    networks:
      - "global_network"

networks:
  global_network:
    external: true
