services:
  tsb_postgres:
    container_name: tsb_postgres
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "tagstickerbot"
      POSTGRES_USER: "tagstickerbot"
      POSTGRES_PASSWORD: "p4ssw0rd"
    volumes:
      - "tsb_postgres_data:/var/lib/postgresql/data"
    networks:
      - "global_network"

networks:
  global_network:
    external: true

volumes:
  tsb_postgres_data:
    driver: local
