export const userSessionAttributes = Object.freeze({
  userId: 'u',
  isPrivate: 'pr',
  stickerSetName: 'set',
  animationMimeType: 'mime',
  fileUniqueId: 'fuid',
  fileId: 'fid',
  fileMessageId: 'smid',
  tagInstructionMessageId: 'timid',
  queueStickerSetBitmap: 'qmap',
  queueStickerSetBitmapLength: 'qmaplen',
  queueStickerSetBitmapSize: 'qmapsize',
  queuePosition: 'qpos',
  phase: 'p',
  expiresAt: 'exp',
})
