export const userSessionAttributes = Object.freeze({
  userId: 'u',
  stickerSetName: 'set',
  stickerFileUniqueId: 'fuid',
  stickerFileId: 'fid',
  stickerFormat: 'fmt',
  stickerEmoji: 'emj',
  stickerMessageId: 'smid',
  tagInstructionMessageId: 'timid',
  queueStickerSetBitmap: 'qmap',
  queueStickerSetBitmapLength: 'qmaplen',
  queueStickerSetBitmapSize: 'qmapsize',
  queuePosition: 'qpos',
  phase: 'p',
  expiresAt: 'exp',
})
