export const MIN_QUERY_LENGTH = 2
export const MAX_QUERY_LENGTH = 20
export const MIN_TAG_VALUE_LENGTH = 2
export const MAX_TAG_VALUE_LENGTH = 100
export const INLINE_QUERY_CACHE_TIME_LOCAL_S = 5
export const INLINE_QUERY_CACHE_TIME_S = 300
export const INLINE_QUERY_RESULT_LIMIT = 2